// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs6uK3lWM02MRubzQNMW6o_jWnydklkPI',
    appId: '1:998211747538:web:4d8c74c18e9cdf2f5db70b',
    messagingSenderId: '998211747538',
    projectId: 'salo-8694a',
    authDomain: 'salo-8694a.firebaseapp.com',
    storageBucket: 'salo-8694a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcbqsnl-_RarHJCJWP_knQ87WW5NqvkDs',
    appId: '1:998211747538:android:99b8e3842d97ff075db70b',
    messagingSenderId: '998211747538',
    projectId: 'salo-8694a',
    storageBucket: 'salo-8694a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_P7SF0NdmiHh3M7LzvHChDZoCasnz78w',
    appId: '1:998211747538:ios:ab46be6f50cd508b5db70b',
    messagingSenderId: '998211747538',
    projectId: 'salo-8694a',
    storageBucket: 'salo-8694a.firebasestorage.app',
    iosBundleId: 'com.example.foodSharing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_P7SF0NdmiHh3M7LzvHChDZoCasnz78w',
    appId: '1:998211747538:ios:ab46be6f50cd508b5db70b',
    messagingSenderId: '998211747538',
    projectId: 'salo-8694a',
    storageBucket: 'salo-8694a.firebasestorage.app',
    iosBundleId: 'com.example.foodSharing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDs6uK3lWM02MRubzQNMW6o_jWnydklkPI',
    appId: '1:998211747538:web:32cd044de0bd13605db70b',
    messagingSenderId: '998211747538',
    projectId: 'salo-8694a',
    authDomain: 'salo-8694a.firebaseapp.com',
    storageBucket: 'salo-8694a.firebasestorage.app',
  );

}